<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ContactSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('contacts')->insert([
            [
                'id' => 1,
                'firstname' => 'Simohamed',
                'lastname' => 'Akniouene',
                'email' => 'akniouene.s@example.com',
                'company_id' => 8,
            ],
            [
                'id' => 2,
                'firstname' => 'Lucineia',
                'lastname' => 'Kunikov',
                'email' => 'kunikov.lucineia@example.com',
                'company_id' => 1,
            ],
            [
                'id' => 3,
                'firstname' => 'Ruiman',
                'lastname' => 'Calleras',
                'email' => 'calleras.r@example.com',
                'company_id' => 3,
            ],
            [
                'id' => 4,
                'firstname' => 'Yaniris',
                'lastname' => 'Haizel',
                'email' => 'yaniris.h@example.com',
                'company_id' => 6,
            ],
            [
                'id' => 5,
                'firstname' => 'Hady',
                'lastname' => 'Jolivera',
                'email' => 'h.jolivera@example.com',
                'company_id' => 4,
            ],
            [
                'id' => 6,
                'firstname' => 'Jadilla',
                'lastname' => 'Cortazar',
                'email' => 'cortazar.jadilla@example.com',
                'company_id' => 2,
            ],
            [
                'id' => 7,
                'firstname' => 'Alyse',
                'lastname' => 'Pahle',
                'email' => 'a.pahle@example.com',
                'company_id' => 1,
            ],
            [
                'id' => 8,
                'firstname' => 'Mehmet',
                'lastname' => 'Erce',
                'email' => 'm.erce@example.com',
                'company_id' => 2,
            ],
            [
                'id' => 9,
                'firstname' => 'Aiyu',
                'lastname' => 'Sukhanov',
                'email' => 'aiyu.sukhanov@example.com',
                'company_id' => 8,
            ],
            [
                'id' => 10,
                'firstname' => 'Angustias',
                'lastname' => 'Mucha',
                'email' => 'mucha.a@example.com',
                'company_id' => 1,
            ],
            [
                'id' => 11,
                'firstname' => 'Arcangel',
                'lastname' => 'Saund',
                'email' => 'arcangel.s@example.com',
                'company_id' => 8,
            ],
            [
                'id' => 12,
                'firstname' => 'Odulia',
                'lastname' => 'Kurynov',
                'email' => 'odulia.kurynov@example.com',
                'company_id' => 3,
            ],
            [
                'id' => 13,
                'firstname' => 'Saiful',
                'lastname' => 'Geschke',
                'email' => 'saiful.geschke@example.com',
                'company_id' => 7,
            ],
            [
                'id' => 14,
                'firstname' => 'Lynetta',
                'lastname' => 'Maetake',
                'email' => 'maetake.l@example.com',
                'company_id' => 3,
            ],
            [
                'id' => 15,
                'firstname' => 'Aycha',
                'lastname' => 'Yatsun',
                'email' => 'a.yatsun@example.com',
                'company_id' => 6,
            ],
            [
                'id' => 16,
                'firstname' => 'Felicisima',
                'lastname' => 'Adajania',
                'email' => 'felicisima.a@example.com',
                'company_id' => 5,
            ],
            [
                'id' => 17,
                'firstname' => 'Ireneusz',
                'lastname' => 'Khujadze',
                'email' => 'khujadze.i@example.com',
                'company_id' => 4,
            ],
            [
                'id' => 18,
                'firstname' => 'Waylon',
                'lastname' => 'Babač',
                'email' => 'waylon.babač@example.com',
                'company_id' => 1,
            ],
            [
                'id' => 19,
                'firstname' => 'Fidencia',
                'lastname' => 'Ehrenstrasser',
                'email' => 'ehrenstrasser.fidencia@example.com',
                'company_id' => 8,
            ],
            [
                'id' => 20,
                'firstname' => 'Sid',
                'lastname' => 'Szarafi',
                'email' => 's.szarafi@example.com',
                'company_id' => 8,
            ],
            [
                'id' => 21,
                'firstname' => 'Celio',
                'lastname' => 'Van der Ploeg',
                'email' => 'van-der-ploeg.c@example.com',
                'company_id' => 5,
            ],
            [
                'id' => 22,
                'firstname' => 'Baldiri',
                'lastname' => 'Vlahek',
                'email' => 'vlahek.b@example.com',
                'company_id' => 4,
            ],
            [
                'id' => 23,
                'firstname' => 'Vanuza',
                'lastname' => 'Rakhmaninov',
                'email' => 'v.rakhmaninov@example.com',
                'company_id' => 8,
            ],
            [
                'id' => 24,
                'firstname' => 'Suleika',
                'lastname' => 'Vuoti',
                'email' => 'vuoti.s@example.com',
                'company_id' => 7,
            ],
            [
                'id' => 25,
                'firstname' => 'Ugo',
                'lastname' => 'Stulić',
                'email' => 'stulić.ugo@example.com',
                'company_id' => 7,
            ],
            [
                'id' => 26,
                'firstname' => 'Mjid',
                'lastname' => 'Hirschhorn',
                'email' => 'mjid.h@example.com',
                'company_id' => 6,
            ],
            [
                'id' => 27,
                'firstname' => 'Malake',
                'lastname' => 'Aronian',
                'email' => 'aronian.malake@example.com',
                'company_id' => 3,
            ],
            [
                'id' => 28,
                'firstname' => 'Navjot',
                'lastname' => 'Maclang',
                'email' => 'navjot.maclang@example.com',
                'company_id' => 4,
            ],
            [
                'id' => 29,
                'firstname' => 'Firdaouss',
                'lastname' => 'Clerc',
                'email' => 'f.clerc@example.com',
                'company_id' => 3,
            ],
            [
                'id' => 30,
                'firstname' => 'Vaclovas',
                'lastname' => 'Reneses',
                'email' => 'vaclovas.r@example.com',
                'company_id' => 4,
            ],
            [
                'id' => 31,
                'firstname' => 'Silmara',
                'lastname' => 'Dubitsky',
                'email' => 's.dubitsky@example.com',
                'company_id' => 5,
            ],
            [
                'id' => 32,
                'firstname' => 'Javiera',
                'lastname' => 'Heinecke',
                'email' => 'j.heinecke@example.com',
                'company_id' => 5,
            ],
            [
                'id' => 33,
                'firstname' => 'Ibtissam',
                'lastname' => 'Giacchino',
                'email' => 'ibtissam.g@example.com',
                'company_id' => 4,
            ],
            [
                'id' => 34,
                'firstname' => 'Kiryl',
                'lastname' => 'Cabilla',
                'email' => 'kiryl.c@example.com',
                'company_id' => 2,
            ],
            [
                'id' => 35,
                'firstname' => 'Salha',
                'lastname' => 'Pipa',
                'email' => 'pipa.s@example.com',
                'company_id' => 5,
            ],
            [
                'id' => 36,
                'firstname' => 'Huria',
                'lastname' => 'Viqueira',
                'email' => 'huria.v@example.com',
                'company_id' => 8,
            ],
            [
                'id' => 37,
                'firstname' => 'Nerijus',
                'lastname' => 'Faki',
                'email' => 'n.faki@example.com',
                'company_id' => 1,
            ],
            [
                'id' => 38,
                'firstname' => 'Carmelina',
                'lastname' => 'Roggeveen',
                'email' => 'carmelina.r@example.com',
                'company_id' => 8,
            ],
            [
                'id' => 39,
                'firstname' => 'Yashira',
                'lastname' => 'Tevanian',
                'email' => 'tevanian.y@example.com',
                'company_id' => 5,
            ],
            [
                'id' => 40,
                'firstname' => 'Lissett',
                'lastname' => 'Ragonot',
                'email' => 'l.ragonot@example.com',
                'company_id' => 5,
            ],
            [
                'id' => 41,
                'firstname' => 'Keesha',
                'lastname' => 'Partain',
                'email' => 'k.partain@example.com',
                'company_id' => 2,
            ],
            [
                'id' => 42,
                'firstname' => 'Abderahmane',
                'lastname' => 'Iturrizabalaga',
                'email' => 'iturrizabalaga.a@example.com',
                'company_id' => 5,
            ],
            [
                'id' => 43,
                'firstname' => 'Yemina',
                'lastname' => 'Ehgartner',
                'email' => 'ehgartner.yemina@example.com',
                'company_id' => 2,
            ],
            [
                'id' => 44,
                'firstname' => 'Lali',
                'lastname' => 'Bajrić',
                'email' => 'lali.bajrić@example.com',
                'company_id' => 8,
            ],
            [
                'id' => 45,
                'firstname' => 'Xantal',
                'lastname' => 'Rezabal',
                'email' => 'x.rezabal@example.com',
                'company_id' => 4,
            ],
            [
                'id' => 46,
                'firstname' => 'Mariko',
                'lastname' => 'Ogburn',
                'email' => 'ogburn.mariko@example.com',
                'company_id' => 5,
            ],
            [
                'id' => 47,
                'firstname' => 'Haddoum',
                'lastname' => 'Kochjohann',
                'email' => 'kochjohann.h@example.com',
                'company_id' => 8,
            ],
            [
                'id' => 48,
                'firstname' => 'Eitan',
                'lastname' => 'Ideman',
                'email' => 'ideman.eitan@example.com',
                'company_id' => 1,
            ],
            [
                'id' => 49,
                'firstname' => 'Marguerite',
                'lastname' => 'Ruschepaul',
                'email' => 'ruschepaul.marguerite@example.com',
                'company_id' => 1,
            ],
            [
                'id' => 50,
                'firstname' => 'Bernardine',
                'lastname' => 'Gaucher',
                'email' => 'bernardine.gaucher@example.com',
                'company_id' => 8,
            ]
        ]);
    }
}
