FROM node:16 AS node
FROM php:7.4-fpm

COPY --from=node /usr/local/lib/node_modules /usr/local/lib/node_modules
COPY --from=node /usr/local/bin/node /usr/local/bin/node
RUN ln -s /usr/local/lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npm

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        git \
        wget \
        gnupg2 \
        libpng-dev \
        libicu-dev \
        libcurl4-openssl-dev \
        libzip-dev \
        libxml2-dev \
    && rm -rf /var/lib/apt/lists/*

RUN curl "https://packages.microsoft.com/keys/microsoft.asc" | apt-key add -
RUN curl "https://packages.microsoft.com/config/ubuntu/22.04/prod.list" > /etc/apt/sources.list.d/mssql-release.list
RUN apt-get update
RUN ACCEPT_EULA=Y apt-get -y --no-install-recommends install msodbcsql17 unixodbc-dev
RUN pecl install sqlsrv-5.9.0
RUN pecl install pdo_sqlsrv-5.9.0
RUN apt-get clean && rm -rf /var/lib/apt/lists

RUN docker-php-ext-configure intl
RUN docker-php-ext-install pdo pdo_mysql gd bcmath intl curl zip soap
RUN docker-php-ext-enable sqlsrv
RUN docker-php-ext-enable pdo_sqlsrv
RUN docker-php-ext-enable soap

RUN wget "https://getcomposer.org/download/latest-2.x/composer.phar"
RUN chmod +x composer.phar
RUN mv composer.phar /usr/local/bin/composer

# Non-root user
ARG UNAME=devuser
ARG UID=1003
ARG GID=1003
RUN groupadd -g $GID $UNAME \
    && useradd -m -u $UID -g $GID -s /bin/bash $UNAME

USER $UNAME
WORKDIR /var/www/html
